jrickard-vmware IPI
redhat-cop/ocp-disconnected-docs pull request #3
Opened 2021-03-11 16:38 UTC by day0hero

Installation walkthrough of OCP 4.7 IPI on vmware. 
@itewk

2021-03-11 16:45 UTC, itewk commented
@claudiol @ckupe can you all review this with @jflowers ?

2021-03-15 21:23 UTC, itewk commented
@claudiol @ckupe  @jflowers ping

2021-03-18 14:01 UTC, jflowers requested changes
Can we get the same major sections and format to match the other docs created so far?
For example:
## Overview
## VMWare Configuration Requirements
### Example VMWare Configuration
## Installing OpenShift
### Bundling Content and Moving it to the Disconnected Environment
### Run OpenShift Install


Also it is nice to indicate what machine commands are being run from. In the other docs this has been noted as a comment in the first line of a code block. For example:
https://github.com/redhat-cop/ocp-disconnected-docs/blob/main/IPIonMAGInstall.md#2-push-bundle-to-registry

2021-03-22 12:54 UTC, itewk commented
@jrickard got time to iterate on this PR with @jflowers ?

2021-03-22 13:31 UTC, day0hero commented on IPIonVMWare.md
> +# Installing OpenShift in vmWare Disconnected using IPI
i just looked on their site - its VMware; I will fix this

2021-03-22 13:44 UTC, day0hero commented on IPIonVMWare.md
> +[vmware permissions](https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html#installation-vsphere-installer-infra-
done.

2021-03-22 13:45 UTC, day0hero commented on IPIonVMWare.md
> +- Using the document above, assign the correct permissions to the role
The documentation doesn't go through creating the role and applying the permissions. If one has experience creating roles and permissions in vcenter this is probably trivial, but if not, at least to me, it wasn't straightforward

2021-03-22 13:50 UTC, day0hero commented on IPIonVMWare.md
> +scp mirror_bundle.tar <ip_of_disconnected_node>:~
Line 111: 
<p class="callout info"> A virtual machine is deployed from the RHEL8 template and is configured with only the internal portgroups.</p>

Do I need to walk through creating a vm using a template? I can do it, but my template names will be different than what they are using...

2021-03-22 13:51 UTC, day0hero commented on IPIonVMWare.md
> +curl -LfO  https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/latest/rhcos-vmware.x86_64.ova
LMK what you want to do with this - my intention was to make it as vanilla (follow the docs as much as possible)

2021-03-22 13:52 UTC, day0hero commented on IPIonVMWare.md
> +curl -k -LfO https://vcenter.fq.dn/certs/download.zip`
changed fq.dn to example.com

2021-04-09 17:05 UTC, itewk commented
my two cents. merge it as is. iterate out the rest later with smaller PRs and such. this is far better then anything else out there (or not out there).

2021-04-21 17:10 UTC, itewk commented
@jflowers can we merge this?

2021-04-21 18:02 UTC, jflowers commented
> @jflowers can we merge this?

I guess so. We have already found that we are getting calls on parts that we didn't explain well. As long as people are ready to field the questions/support go for it

2021-04-21 23:07 UTC, day0hero commented
@

> > @jflowers can we merge this?
> 
> I guess so. We have already found that we are getting calls on parts that we didn't explain well. As long as people are ready to field the questions/support go for it

What are the parts that aren't explained well and I will make the corrections

2021-04-23 14:37 UTC, itewk commented
@day0hero @jflowers how about, lets merge, cuz this in its current state is better then nothing/anything else. and then can do follow on prs to make better as people use and find enahcments. perfect / enemy / good and all that.

2021-04-23 14:50 UTC, jflowers commented
> @day0hero @jflowers how about, lets merge, cuz this in its current state is better then nothing/anything else. and then can do follow on prs to make better as people use and find enahcments. perfect / enemy / good and all that.

Go for it @itewk

2021-04-23 15:00 UTC, merged